name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./WebApp/frontend # Kontekst gradnje za frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/geometrics:frontend # Tag za frontend sliko
          file: ./WebApp/frontend/Dockerfile # Eksplicitna pot do Dockerfile

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./WebApp/backend # Kontekst gradnje za backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/geometrics:backend # Tag za backend sliko
          file: ./WebApp/backend/Dockerfile # Eksplicitna pot do Dockerfile

  send-webhook-notification:
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"api-key": "${{ secrets.WEBHOOK_API_KEY }}"}'
          body: '{"event": "deployment", "repository": "${{ github.repository }}"}'
          insecure: true
          github_event_payload: true
